"""Dense semantic retrieval baseline for TraceWise."""

from __future__ import annotations

from collections.abc import Callable, Sequence
from typing import Any

import numpy as np

from tracewise.preprocessing.models import ProcessedText
from tracewise.retrieval.base import BaseRetriever
from tracewise.retrieval.exceptions import NotIndexedError
from tracewise.retrieval.models import RetrievalCandidate

EmbedderFunc = Callable[[Sequence[str]], np.ndarray]


def _default_fastembed_factory(model_name: str) -> EmbedderFunc:
    """Create a default embedding callable using fastembed if installed.

    Args:
        model_name: Pretrained embedding model name identifier.

    Returns:
        Callable that embeds a sequence of strings into a float32 ndarray
        of shape (N, D).

    Raises:
        ImportError: If fastembed is not installed.
    """
    try:
        from fastembed import TextEmbedding
    except ImportError as exc:
        raise ImportError(
            "fastembed is required for the default semantic embedding backend. "
            "Please install fastembed or provide an explicit 'embedder' callable "
            "to SemanticRetriever."
        ) from exc

    model = TextEmbedding(model_name=model_name)

    def _embedder(texts: Sequence[str]) -> np.ndarray:
        if not texts:
            return np.empty((0, 0), dtype=np.float32)
        embeddings = list(model.embed(texts))
        return np.asarray(embeddings, dtype=np.float32)

    return _embedder


def _normalize_embeddings(vectors: np.ndarray) -> np.ndarray:
    """L2-normalize row vectors safely, leaving zero vectors as zero.

    Args:
        vectors: 2D array of shape (N, D).

    Returns:
        L2-normalized 2D array of shape (N, D).
    """
    if vectors.size == 0 or vectors.ndim != 2:
        return vectors
    norms = np.linalg.norm(vectors, axis=1, keepdims=True)
    # Replace zero or near-zero norms with 1.0 to avoid zero division
    safe_norms = np.where(norms < 1e-12, 1.0, norms)
    # For vectors whose original norm was 0, their result is 0 / 1.0 = 0
    normalized = vectors / safe_norms
    normalized[norms.squeeze(axis=-1) < 1e-12] = 0.0
    return normalized


class SemanticRetriever(BaseRetriever):
    """Dense semantic retrieval baseline using text embeddings and cosine similarity.

    Algorithm specification (Milestone 4A):
    - Text Representation: Preprocessed query and document text extracted from
      `doc.normalized_text`. If normalized_text is empty or blank, falls back to
      `" ".join(doc.tokens)`.
    - Embedding: Dense vector representation generated by a pretrained embedding model
      or user-supplied embedder callable.
    - Vector Normalization: L2 normalization of document and query vectors:
        v_norm = v / max(||v||_2, 1e-12)
    - Similarity Metric: Cosine similarity via inner product of normalized vectors:
        cos_sim(q, d) = <q_norm, d_norm>
    - Score Clamping: Cosine similarity scores are clamped to [0.0, 1.0] to guarantee
      well-behaved non-negative scores.
    - Determinism: Ties are broken deterministically by target_id ascending:
        key=lambda candidate: (-candidate.score, candidate.target_id)
    - Ranks: 1-based and consecutive (1, 2, 3, ...).
    """

    retriever_name: str = "semantic"

    def __init__(
        self,
        model_name: str = "sentence-transformers/all-MiniLM-L6-v2",
        embedder: EmbedderFunc | None = None,
        **kwargs: Any,
    ) -> None:
        """Initialize SemanticRetriever with configurable model or custom embedder.

        Args:
            model_name: Pretrained embedding model identifier
                (default: all-MiniLM-L6-v2).
            embedder: Optional embedding callable taking Sequence[str] and returning
                np.ndarray of shape (N, D). If None, defaults to fastembed backend.
            **kwargs: Extra parameters reserved for future extension.
        """
        self.model_name = model_name
        self._custom_embedder = embedder
        self._embedder_func: EmbedderFunc | None = embedder
        self._kwargs = kwargs

        self._is_indexed: bool = False
        self._target_ids: list[str] = []
        self._doc_embeddings: np.ndarray = np.empty((0, 0), dtype=np.float32)
        self._dim: int = 0

    @property
    def is_indexed(self) -> bool:
        """Whether the retriever has an active index ready for querying."""
        return self._is_indexed

    def _get_embedder(self) -> EmbedderFunc:
        """Get or lazily initialize the embedding function."""
        if self._embedder_func is None:
            self._embedder_func = _default_fastembed_factory(self.model_name)
        return self._embedder_func

    @staticmethod
    def _extract_text(doc: ProcessedText) -> str:
        """Extract indexing/query text from ProcessedText."""
        norm = doc.normalized_text.strip()
        if norm:
            return norm
        return " ".join(doc.tokens).strip()

    def index(self, documents: Sequence[ProcessedText]) -> None:
        """Build or replace the retriever's target index with documents.

        Calling index again replaces the previous index completely. If indexing
        fails for any reason, the prior valid state remains unchanged.

        Args:
            documents: Sequence of preprocessed text documents to index.

        Raises:
            ValueError: If documents is empty, contains duplicate source_ids,
                or embedding produces invalid dimensions.
        """
        doc_list = list(documents)
        if not doc_list:
            raise ValueError("Cannot index an empty document sequence.")

        target_ids: list[str] = []
        seen_ids: set[str] = set()
        for doc in doc_list:
            sid = doc.source_id
            if sid in seen_ids:
                raise ValueError(f"Duplicate document source_id found: '{sid}'.")
            seen_ids.add(sid)
            target_ids.append(sid)

        texts = [self._extract_text(doc) for doc in doc_list]
        embedder = self._get_embedder()
        raw_embs = np.asarray(embedder(texts), dtype=np.float32)

        if raw_embs.ndim != 2 or raw_embs.shape[0] != len(doc_list):
            raise ValueError(
                f"Embedder returned shape {raw_embs.shape}, "
                f"expected ({len(doc_list)}, D)."
            )

        dim = raw_embs.shape[1]
        doc_embeddings = _normalize_embeddings(raw_embs)

        # Atomic commit to object state only after all operations succeed
        self._target_ids = target_ids
        self._doc_embeddings = doc_embeddings
        self._dim = dim
        self._is_indexed = True

    def retrieve(
        self,
        query: ProcessedText,
        top_k: int | None = None,
    ) -> list[RetrievalCandidate]:
        """Retrieve candidate matches for a query from the indexed corpus.

        Candidates are scored using cosine similarity between query and document
        dense embeddings, clamped to [0.0, 1.0], and sorted by (-score, target_id)
        with 1-based ranks.

        Args:
            query: Preprocessed query to search against indexed documents.
            top_k: Optional maximum number of candidates to return.
                If None, returns all candidates for the query.

        Returns:
            List of RetrievalCandidate objects ordered by descending score.

        Raises:
            NotIndexedError: If retrieve is called before index.
            ValueError: If top_k is less than or equal to 0.
        """
        if not self._is_indexed:
            raise NotIndexedError(
                f"Retriever '{self.retriever_name}' cannot retrieve before indexing."
            )

        if top_k is not None and top_k <= 0:
            raise ValueError(f"top_k must be strictly positive, got {top_k}.")

        num_docs = len(self._target_ids)
        if num_docs == 0:
            return []

        q_text = self._extract_text(query)
        embedder = self._get_embedder()

        if not q_text.strip():
            # Blank/empty query produces 0 similarity across all targets
            scores = np.zeros(num_docs, dtype=np.float32)
        else:
            q_emb_raw = np.asarray(embedder([q_text]), dtype=np.float32)
            if q_emb_raw.ndim != 2 or q_emb_raw.shape[0] != 1:
                raise ValueError(
                    f"Embedder for query returned shape {q_emb_raw.shape}, "
                    "expected (1, D)."
                )
            if self._dim > 0 and q_emb_raw.shape[1] != self._dim:
                raise ValueError(
                    f"Query embedding dimension {q_emb_raw.shape[1]} does not match "
                    f"indexed dimension {self._dim}."
                )

            q_norm = _normalize_embeddings(q_emb_raw)[0]
            scores = self._doc_embeddings.dot(q_norm)

        # Pair target_ids with clamped float scores
        raw: list[tuple[str, float]] = []
        for idx, target_id in enumerate(self._target_ids):
            score = float(scores[idx])
            clamped_score = max(0.0, min(1.0, score))
            raw.append((target_id, clamped_score))

        # Shared contract ordering: (-score, target_id)
        raw.sort(key=lambda item: (-item[1], item[0]))

        if top_k is not None:
            raw = raw[:top_k]

        return [
            RetrievalCandidate(
                query_id=query.source_id,
                target_id=target_id,
                score=score,
                rank=rank,
                retriever_name=self.retriever_name,
            )
            for rank, (target_id, score) in enumerate(raw, start=1)
        ]


__all__ = ["SemanticRetriever"]
